import { Geist, Geist_Mono} from "next/font/google";
import UserProvider  from "@/src/components/provider/UserProvider";
import type { Metadata } from "next";
import Nav from "@/src/components/nav/Nav"
import "./globals.css";
import { Api } from "@/src/lib/api"
import { cookies } from "next/headers";
import SocketProvider from "../components/provider/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans", 
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout( {
  children,
}: Readonly< {
  children: React.ReactNode;
}>) {

  let user = null;
  const accessToken = (await cookies()).get("accessToken")?.value;
  if (accessToken)
    user = await Api.getUser(accessToken || "").then(r => r.json());
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} >
      <body className="min-h-full flex flex-col min-w-md">
        <UserProvider initialUser={user}>
           <Nav />
          <SocketProvider>
            {children}
          </SocketProvider>
        </UserProvider>
      </body>
    </html>
  );
}
