services:
  frontend:
    build:
      context: ./frontend
      target: prod
    volumes: !override []

  backend:
    build:
      context: ./backend
      target: prod  
    volumes:
      - avatars:/uploads/avatars
    command: >
      sh -c "
      npx prisma db push --schema=/app/prisma/schema.prisma &&
      npx prisma generate --schema=/app/prisma/schema.prisma && 
      npm run seed &&
      npm run seed:admin &&
      node dist/main.js
      "
